name: Docker (cannery)

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
    inputs:
      katapultVer:
        description: Katapult Version
        type: string
        required: true
      katapultRepo:
        description: Katapult repo to use
        type: choice
        options:
          - https://github.com/arksine/Katapult.git
      tagName:
          description: Tag to create
          type: string
          required: true

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}/cannery


jobs:
  build_cannery:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          submodules: true

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images:
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ inputs.tagName }}


      - name: Docker Build
        uses: docker/build-push-action@v5
        with:
          context: ./cannery-container
          file: ./cannery-container/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            canboot_repo=${{ inputs.canBootRepo }}
            canboot_ref=${{ inputs.canBootVer }}
          cache-from: type=gha
          cache-to: type=gha,mode=max