name: Factory Build (single)

on:
  workflow_dispatch:
    inputs:
      factoryTag:
        description: The factory tag to use when building
        type: string
        required: true
      configName:
        description: Config Name
        type: string
        required: true
      configLiteralb64gz:
        description: base64+gzip-encoded config
        type: string
        required: false
      configURL:
        description: URL to download config from
        type: string
        required: false
      configPath:
        description: Path in this repo of config to use
        type: string
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup build environment
        env:
          CONFIG_LITERAL: "${{inputs.configLiteralb64gz}}"
          CONFIG_URL: "${{inputs.configURL}}"
          CONFIG_PATH: "${{inputs.configPath}}"
          CONFIG_NAME: "${{inputs.configName}}"
          FACTORY_TAG: "${{inputs.factoryTag}}"
        run: |
          set -x
          tmp_dir="$(mktemp -d -t klipperfactory.XXXXXXXXXX)"
          if [[ $CONFIG_LITERAL ]]; then
            base64 -d <<<"$CONFIG_LITERAL" | gunzip > "$tmp_dir/$CONFIG_NAME.config"
          elif [[ $CONFIG_URL ]]; then
            curl --fail -L "$CONFIG_URL" > "$tmp_dir/$CONFIG_NAME.config"
          elif [[ $CONFIG_PATH ]]; then
            cp "$CONFIG_PATH" "$tmp_dir/$CONFIG_NAME.config"
          else
            echo >&2 "Unable to locate config file"
            exit 2
          fi
          mkdir "$tmp_dir/out"
          setfacl -Rm u:1000:rX "$tmp_dir"
          setfacl -m u:1000:rwX "$tmp_dir/out"
          docker run --rm -v "$tmp_dir":/mnt:z "ghcr.io/laikulo/klipper-firmware/factory:$FACTORY_TAG" -c "/mnt/$CONFIG_NAME.config" -o /mnt/out
