name: Factory Build (All Configs)

on:
  workflow_dispatch:
    inputs:
      factoryTag:
        description: The factory tag to build
        type: string
        required: true

jobs:
  build_firmware_all:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      #release: write
    steps:
      - uses: actions/checkout@v4
      - name: Build all firmware configs for klipper
        run: |
          $PWD/.github/factory-build-all.sh ${{ inputs.factoryTag }}
      - name: Archive resultant builds
        uses: actions/upload-artifact@v4
        with:
          name: firmware_bundles
          path: dist/*.tar.gz
          if-no-files-found: fail
          compression-level: 0 
    #TODO: Publish somehow